# Site settings
title: A Geek's Perspective
description: 'Mainly blogging about programming, machine learning, driving assistance systems, self driving cars.'
#url: 'http://127.0.0.1:4000'
url: 'http://mbornoe.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Morten Bornø Jensen'
  email: mboj@create.aau.dk
  twitter_username: mbornoe
  facebook_username: mbornoe
  github_username:  mbornoe
  linkedin_username:  mbornoe

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
